# src/contexts/tweet/tweet.schema.ts

type Tweet {
	id: ID!
	content: String!
	likes: Int!
	media: [String!]!
	createdAt: DateTimeISO!
	author: User!
}

extend type Query {
	tweets: [Tweet!]! @auth
}

extend type Mutation {
	createTweet(content: String!, media: [String!]! = []): Tweet! @auth
}
